import JSZip from 'jszip';
import { load } from 'cheerio';
import dns from 'node:dns/promises';
import net from 'node:net';

const MAX_FILES=100, MAX_FILE=3_000_000, MAX_TOTAL=22_000_000;
function privateIP(ip){
 if(net.isIP(ip)===4){const a=ip.split('.').map(Number);return a[0]===0||a[0]===10||a[0]===127||a[0]>=224||(a[0]===169&&a[1]===254)||(a[0]===172&&a[1]>=16&&a[1]<=31)||(a[0]===192&&a[1]===168)||(a[0]===100&&a[1]>=64&&a[1]<=127)||(a[0]===192&&a[1]===0)||(a[0]===198&&(a[1]===18||a[1]===19));}
 const v=ip.toLowerCase();return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe8')||v.startsWith('fe9')||v.startsWith('fea')||v.startsWith('feb')||v.startsWith('::ffff:');
}
async function safeUrl(input){const u=new URL(input);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.port&& !['80','443'].includes(u.port)||u.hostname==='localhost'||u.hostname.endsWith('.local')||net.isIP(u.hostname))throw Error('Use a publicly accessible HTTP(S) website URL.');const addresses=await dns.lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(x=>privateIP(x.address)))throw Error('Private or internal network addresses are not allowed.');return u;}
async function get(url){let current=url;for(let n=0;n<4;n++){await safeUrl(current);const res=await fetch(current,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'user-agent':'SiteHarvestStudio/1.0 (+public-page-export)','accept':'text/html,text/css,application/javascript,image/*,*/*'}});if(res.status>=300&&res.status<400&&res.headers.get('location')){current=new URL(res.headers.get('location'),current).href;continue;}if(!res.ok)throw Error(`Request failed (${res.status})`);const length=Number(res.headers.get('content-length')||0);if(length>MAX_FILE)throw Error('Individual resource exceeds 3 MB limit.');const reader=res.body.getReader();let chunks=[],size=0;while(true){let {value,done}=await reader.read();if(done)break;size+=value.length;if(size>MAX_FILE){await reader.cancel();throw Error('Individual resource exceeds 3 MB limit.');}chunks.push(value);}return {buffer:Buffer.concat(chunks),contentType:res.headers.get('content-type')||'',url:current};}throw Error('Too many redirects.');}
function nameFor(url,idx){const u=new URL(url);let p=decodeURIComponent(u.pathname.split('/').pop()||'resource').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,65);if(!p.includes('.'))p+='.'+(/\.css(\?|$)/.test(url)?'css':/\.js(\?|$)/.test(url)?'js':'bin');return `assets/${String(idx).padStart(3,'0')}-${p}`;}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{let body=typeof req.body==='string'?JSON.parse(req.body):req.body;const raw=String(body?.url||'').trim();if(raw.length>2048)throw Error('URL too long.');const target=await safeUrl(raw);const main=await get(target.href);if(!/text\/html|application\/xhtml\+xml/i.test(main.contentType))throw Error('This URL did not return an HTML page.');const $=load(main.buffer.toString('utf8'));const resources=new Map();function add(raw,kind){if(!raw||raw.startsWith('data:')||raw.startsWith('blob:')||raw.startsWith('javascript:'))return;try{const u=new URL(raw,main.url);if(['http:','https:'].includes(u.protocol)&&u.origin===new URL(main.url).origin){u.hash='';if(!resources.has(u.href))resources.set(u.href,kind);}}catch{}}
 $('link[href]').each((_,e)=>{const rel=($(e).attr('rel')||'').toLowerCase();if(/stylesheet|icon|preload|modulepreload/.test(rel))add($(e).attr('href'),'link')});$('script[src]').each((_,e)=>add($(e).attr('src'),'script'));$('img[src],source[src],video[poster],audio[src],video[src]').each((_,e)=>add($(e).attr('src')||$(e).attr('poster'),'media'));$('[srcset]').each((_,e)=>{for(const entry of ($(e).attr('srcset')||'').split(','))add(entry.trim().split(/\s+/)[0],'media')});const cssUrls=[...$('style').toArray()].flatMap(e=>[...($(e).html()||'').matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)].map(x=>x[1]));cssUrls.forEach(x=>add(x,'inline-css'));
 const zip=new JSZip();const results=[];let total=main.buffer.length;const pairs=[];for(const [u,kind] of resources){if(pairs.length>=MAX_FILES)break;pairs.push([u,kind]);}let i=0;for(const [u,kind] of pairs){try{const asset=await get(u);if(total+asset.buffer.length>MAX_TOTAL)break;total+=asset.buffer.length;const filename=nameFor(u,++i);zip.file(filename,asset.buffer);results.push({url:u,file:filename,type:asset.contentType,bytes:asset.buffer.length,kind});}catch(e){results.push({url:u,error:e.message,kind});}}
 const map=new Map(results.filter(r=>r.file).map(r=>[r.url,r.file]));function relative(v){try{return map.get(new URL(v,main.url).href)||v}catch{return v}}
 $('link[href],script[src],img[src],source[src],audio[src],video[src],video[poster]').each((_,e)=>{for(const key of ['href','src','poster']){const v=$(e).attr(key);if(v)$(e).attr(key,relative(v))}});
 $('[srcset]').each((_,e)=>{const v=$(e).attr('srcset');if(v)$(e).attr('srcset',v.split(',').map(x=>{const s=x.trim().split(/\s+/);s[0]=relative(s[0]);return s.join(' ')}).join(', '))});
 const html=$.html();zip.file('index.html',html);zip.file('original.html',main.buffer);const hasGSAP=/(gsap|scrolltrigger|scrollsmoother|splittext)/i.test(html)||results.some(x=>/gsap|scrolltrigger/i.test(x.url));zip.file('manifest.json',JSON.stringify({source:main.url,capturedAt:new Date().toISOString(),resourceCount:results.filter(x=>x.file).length,gsapDetected:hasGSAP,resources:results,limitations:['Static public resources only. JavaScript-executed requests and animation states are not captured.','Cross-origin assets are not downloaded.','Some CSS asset references may still point to their original URL.','This is not a complete runnable clone of the original website.']},null,2));zip.file('README.txt','SiteHarvest Studio — public webpage resource export\nOpen index.html to inspect. Some dynamic features and resources may require the original website. GSAP motion is not automatically reconstructed.\n');const buf=await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE',compressionOptions:{level:5}});res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition','attachment; filename="siteharvest-export.zip"');res.setHeader('Cache-Control','no-store');return res.status(200).send(buf);
 }catch(e){return res.status(400).json({error:e.message||'Capture failed.'})}}
